version: "3"


services: 
    monolithic:
        build: ./src/monolithic
    auth:
        build: ./src/microservices/auth-service
  
    nginx:
        image: nginx:latest
        ports: 
            - "8080:8080"
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - monolithic
            - auth
         
        links: 
            - mongo
    mongo:
        container_name: mongo-bd
        image: mongo
        ports: 
            - "27018:27017"
        logging:
            driver: none
        




    
